theme: jekyll-theme-cayman

# Configuramos Jekyll para que aplique el layout del tema a TODO automáticamente
defaults:
  - scope:
      path: "" # Se aplica a todos los archivos del repositorio
    values:
      layout: "default" # Fuerza el layout por defecto de Cayman remoto
